title: Moonwalk Template
author: Zohan Subhash
url: https://web.zohan.tech/moonwalk-template-test # root address of the site
description: Template for generating a Jekyll website based on the Moonwalk (@abhinavs/moonwalk) theme
permalink: /:slug

favicon: "./logo.png" # relative path to site's favicon

# remote_theme: abhinavs/moonwalk
theme: moonwalk # if you are using GitHub Pages, change it to # remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  back_home_text: "home.." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer
  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: false # show blog posts added in _posts
  show_old_projects: false # show old projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml
  show_reading_time: false # show number of words and reading time in the blog posts
  # options for "home" page
  home:
    title_projects: Portfolio

highlighter: rouge

sass:
  style: :compressed

include: ['posts']

twitter:
    card: summary_large_image
  
plugins:
  - jekyll-soopr-seo-tag

destination: docs/
